### ISSUE TITLE
Add utf8 check to assertStorable

### ISSUE THREAD

**Issue by checkraisefold** [anthony0br/DocumentService#68]
https://gist.github.com/TheGreatSageEqualToHeaven/e0e1dc2698307c93f6013b9825705899
Talked about this in the Roblox OSS discord a while ago. `utf8.len` should work

**Comment by anthony0br** [comment]
Technically this is a bug (albeit minor) since assertStorable is meant to catch all cases where data can’t be stored.

Also considering an option to run storability checks on cache updates.

Very constrained for time at the moment though so any PRs relating to this would be really welcome.

**Comment by checkraisefold** [comment]
> Technically this is a bug (albeit minor) since assertStorable is meant to catch all cases where data can’t be stored.
> 
> Also considering an option to run storability checks on cache updates.
> 
> Very constrained for time at the moment though so any PRs relating to this would be really welcome.

as you wish
#69
